### ISSUE TITLE
Support 'windows' terminal type.

### ISSUE THREAD

**Issue by aero** [PDLPorters/PDL-Graphics-Simple#2]
HI,
In Strawberry Perl 5.20 PDL edition
http://strawberryperl.com/download/5.20.0.1/strawberry-perl-5.20.0.1-32bit-PDL.zip
http://strawberryperl.com/download/5.20.0.1/strawberry-perl-5.20.0.1-64bit-PDL.zip

@kmx ( https://github.com/kmx ) puts his own compiled gnuplot 4.6.5 binary in that files.
It only supports 'windows' terminal type.
(it seems that it is different from the official gnuplot distribution http://sourceforge.net/projects/gnuplot/files/gnuplot/4.6.5/ which support 'wxt' terminal type.)

but PDL::Graphics::Simple supports 'x11' and 'wxt'.

Can PDL::Graphics::Simple support 'windows' terminal type?

**Comment by drzowie** [comment]
Hmmm... 

OK, it appears that the "windows" terminal doesn't support the "persist" option.  I went ahead and added a switch to support terminals without that option (windows and aero).  Give that a whirl.  It may fail the interactive test "window disappeared".  If so, I'd appreciate any input you may have on how to destroy a 'windows' terminal display window.

Cheers,
Craig

**Comment by mohawk2** [comment]
I'm going to close this on the assumption that the above (and patches on `master` by Craig) fixed this. I will be releasing an updated version to CPAN shortly (as soon as I've fixed https://rt.cpan.org/Ticket/Display.html?id=86275), and will ask you to try that and report issues!
