### ISSUE TITLE
Add support for retrieving device types per engine

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/PDL-Graphics-Simple#5]
Something like `list_devices`. As these are going to be different for each
engine, perhaps standardizing info about the devices might be useful (e.g.,
using MIME types for files). Some of this information could be directly placed
in the upstream dists.

**Comment by mohawk2** [comment]
This is now implemented in https://github.com/PDLPorters/PDL-Graphics-Simple/commit/3d7f16fcd4ae11b3606de95319169b36db71b8d6 (PGPLOT, which always had the API available) and https://github.com/PDLPorters/PDL-Graphics-Simple/commit/d674bea4c9571681844a717265cbed21f6713d4c (PLplot, with API added by you).

**Comment by zmughal** [comment]
Right, I think I wanted to provide a devices to MIME types / file extension mapping as well because each engine uses different names. This can be done in a future API after the backend split. The idea behind this is that other code can inspect the devices available and choose from that given a requested filename. I believe this could be incorporated for Jupyter notebook support (right now I use P::G::Gnuplot directly in most of my notebooks).

One issue: there might be multiple devices that support the same output type (multiple PNG backends).

**Comment by mohawk2** [comment]
Do feel free to reopen this, if you can provide example code that the user would run. PGS is absolutely the right place to have that uniform-ised interface!
